spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.seed.enabled=${APP_SEED_ENABLED:false}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
